"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "visionTuner",
//   description: "Generated by visionTuner",
// };

import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
  SettingOutlined,
} from "@ant-design/icons";
import { Layout, Menu, Button, theme } from "antd";

import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";

import "../../styles/dashboard.css";
import Projects from "../../components/Pages/Projects";

const { Header, Sider, Content } = Layout;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const [collapsed, setCollapsed] = useState(false);
  // const [key, setkey] = useState("1");

  const handleMenuItemClick = (key: string) => {
    //setkey(key);

    switch (key) {
      case "1":
        router.push("/dashboard/profile");
        break;

      case "2":
        router.push("/dashboard/projects");
        break;

      case "3":
        router.push("/dashboard/settings");
        break;

      default:
        break;
    }
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout className="dashboard">
          <Sider trigger={null} collapsible collapsed={collapsed}>
            <div className="demo-logo-vertical" />
            <Menu
              theme="dark"
              mode="inline"
              defaultSelectedKeys={["1"]}
              onSelect={(e) => handleMenuItemClick(e.key)}
              items={[
                {
                  key: "1",
                  icon: <UserOutlined />,
                  label: "Profile",
                },
                {
                  key: "2",
                  icon: <UploadOutlined />,
                  label: "Projects",
                },
                {
                  key: "3",
                  icon: <SettingOutlined />,
                  label: "Settings",
                },
              ]}
            />
          </Sider>

          <Layout>
            <Header style={{ padding: 0, background: "white" }}>
              <Button
                type="text"
                icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
                onClick={() => setCollapsed(!collapsed)}
                style={{
                  fontSize: "16px",
                  width: 64,
                  height: 64,
                }}
              />
            </Header>

            <Content>{children}</Content>
          </Layout>
        </Layout>
      </body>
    </html>
  );
}
